### ISSUE TITLE
Question about setting map

### ISSUE THREAD

**Issue by ShuaiZhou302** [FE-LAK/PyCCBS#1]
Hello! Is it support map file, like the file in the [Mapf benchmark](https://movingai.com/benchmarks/mapf/index.html), i try to apply my map and i kinda dont get what information is needed to get from the xml file.

![map](https://github.com/FE-LAK/PyCCBS/assets/142286497/504c45e6-9dae-44d3-9e74-5b226b12638a)
for example like this kinds of file, where @ is obstacle and . is places that available

Thank you!

**Comment by matevzsi** [comment]
The library explicitly targets graph-based maps. You can convert the map you have to a 4-way connected graph and use that in the algorithm.

**Comment by ShuaiZhou302** [comment]
thank you!, you mean like convert it to the xml file as you used?

**Comment by matevzsi** [comment]
That is correct. As noted, the project targets graph-based maps and not the grid-based, but this conversion is possible.
